"""Application-wide configuration settings."""

from .base_config import (
    CURRENT_DIRECTORY,
    SRC_DIRECTORY,
    ASSETS_DIRECTORY,
    IMAGES_DIRECTORY,
    TEMP_DIRECTORY,
    TEMP_IMAGE_FILE,
    TRANSFORM_IMAGE_FILE
)
from ..presentation.ui.ui_config import (
    UI_THEME,
    UI_FONT,
    WINDOW_SIZE,
    EMPTY_IMAGE_PATH
)

__all__ = [
    'CURRENT_DIRECTORY',
    'SRC_DIRECTORY',
    'ASSETS_DIRECTORY',
    'IMAGES_DIRECTORY',
    'TEMP_DIRECTORY',
    'TEMP_IMAGE_FILE',
    'TRANSFORM_IMAGE_FILE',
    'UI_THEME',
    'UI_FONT',
    'WINDOW_SIZE',
    'EMPTY_IMAGE_PATH',
    'GAUSSIAN_KERNEL_SIZE',
    'GAUSSIAN_SIGMA',
    'DILATION_KERNEL_SIZE',
    'DEFAULT_MIN_THRESHOLD',
    'DEFAULT_MAX_THRESHOLD'
]