"""Application-wide configuration settings."""

from .base_config import (
    CURRENT_DIRECTORY,
    SRC_DIRECTORY,
    ASSETS_DIRECTORY,
    IMAGES_DIRECTORY,
    TEMP_DIRECTORY
)
from ..presentation.ui.ui_config import (
    UI_THEME,
    UI_FONT,
    WINDOW_SIZE,
    EMPTY_IMAGE_PATH
)
from ..services.processing_config import (
    GAUSSIAN_KERNEL_SIZE,
    GAUSSIAN_SIGMA,
    DILATION_KERNEL_SIZE,
    DEFAULT_MIN_THRESHOLD,
    DEFAULT_MAX_THRESHOLD,
    SUPPORTED_FORMATS,
    TEMP_IMAGE_FILE,
    TRANSFORM_IMAGE_FILE
)

__all__ = [
    'CURRENT_DIRECTORY',
    'SRC_DIRECTORY',
    'ASSETS_DIRECTORY',
    'IMAGES_DIRECTORY',
    'TEMP_DIRECTORY',
    'UI_THEME',
    'UI_FONT',
    'WINDOW_SIZE',
    'EMPTY_IMAGE_PATH',
    'GAUSSIAN_KERNEL_SIZE',
    'GAUSSIAN_SIGMA',
    'DILATION_KERNEL_SIZE',
    'DEFAULT_MIN_THRESHOLD',
    'DEFAULT_MAX_THRESHOLD',
    'SUPPORTED_FORMATS',
    'TEMP_IMAGE_FILE',
    'TRANSFORM_IMAGE_FILE'
]